#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width 2
bspc config window_gap 6

bspc config split_ratio 0.50

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

#bspc config normal_border_color "#1f1b23"
#bspc config focused_border_color "#8575d6"
bspc config normal_border_color "#414868"
bspc config focused_border_color "#7aa2f7"

bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config single_monocle true

bspc config top_monocle_padding 200
bspc config bottom_monocle_padding 200
bspc config right_monocle_padding 600
bspc config left_monocle_padding 600

#AutoStart
sxhkd &
picom --config ~/.config/picom/picom.conf &
nitrogen --restore &
dunst &
unclutter --jitter 10 --ignore-scrolling --start-hidden --fork
. ~/.config/polybar/launch.sh &
